### PR TITLE
PR for #7: Add recent MW data

### PR DESCRIPTION
**Pull request by diegogentilepassaro**
Time to PR this issue! 

@santiagohermo probably it is a good idea that you review my work and I review yours. After we closed #19 I have updated the issue #7 branch with master and I have committed a fresh run. There I have implemented some minor changes to base and derived that you should please review as part of this PR. The only not obvious change that I've implemented was to remove a part under \derived\label_final_dta in which we were eliminating zipcode-months without min-wage information. This was causing the panel to be unbalanced and we need a balanced panel for our event-studies to properly estimate FEs. Also, this shouldn't be happening as all zipcodes are assigned to some county which belongs to some state that either has a MW of its own or it has the federal one. This made me think that we need to think deeper about (i) the zipcode-county match (for example, there are also zipcode-months that we don't assign to a city because city and placename don't coincide). Probably, a good follow-up task although might be possible to improve during this PR.

Also, we should think deeper of (ii) what is the MW event that we consider. Is it the min, mean or the max? Do we include the special MW cases? What to do with the negative MW changes (when the binding MW goes down)? Another potential follow-up task that we can start thinking about how to make better in this PR. This matters in the code in this branch because we are using only min_events of at least $0.5. A question about this last thing: did we changed the analysis as per the changes in derived per [this comment](https://github.com/diegogentilepassaro/min_wage_rent/issues/7#issuecomment-601297259)?

The main PR work here is to check each others work:

- Do the changes in zipcode-months are consistent with the changes that we did? 

- Do we have outliers? Did we added them now or they where here before? (these together with (i) and (ii) might help understand the bumps)

- Did we miss some county or state changes? 

- Do the zipcodes that we are dropping  for the event-studies (either because they are missing or because they are not in an MSA) make sense? 

Feel free to add other questions that are important and I might be missing. Also, @gabrieleborg feel free to check our work and give your thoughts on the questions above!

### CODE REVIEW

**Comment by gabrieleborg** [comment]
I haven't run it yet cause I'm having trouble with my laptop today. My good to go on the review pertains simply to code. I will check Diego's PR tasks as soon as I fix the issues I'm having.

**Comment by santiagohermo** [comment]
I reviewed the state changes @diegogentilepassaro. All the ones I reviewed were correct. I also:
- added some of the MW changes after 31 dec 2019, since we may want to use them later.
- highlighted cells that add new information to the original version of the file (as in the substate level file).

I noted that many states have a tipped minimum wage which we are not adding (for example, [colorado](https://www.colorado.gov/pacific/cdle/minimumwage)). Should we add it? (fyi @gabrieleborg)

---
A couple of extra comments:
- Another interesting source for MW changes is https://www.laborlawcenter.com/state-minimum-wage-rates/
- Per our discussion in the last call we may want to add a dummy indicator that equals 1 if the MW change was pre-announced. We can tackle this in a follow-up issue in the future, for now I added it to [the outline](https://github.com/diegogentilepassaro/min_wage_rent/wiki/Outline#data)

**Comment by gabrieleborg** [comment]
Thanks @santiagohermo for your comments. I don't think we need to add tipped minimum wage, and [here](https://github.com/diegogentilepassaro/min_wage_rent/pull/23#issue-395367837) I explain why. 

I started thinking how to deal with pre-announced changes as well. It will involve some reasoning though so I agree on putting it in the outline for now and open a new issue in the future

**Comment by gabrieleborg** [comment]
Let's merge this? @diegogentilepassaro @santiagohermo

**Comment by diegogentilepassaro** [comment]
Awesome work @santiagohermo! Good idea to add to the outline the tipped wage. 

Just finished reviewing some instances of your substate additions and they also look good. I will go ahead and merge this.

**Pull request merged**
