### PR TITLE
PR for #109: New draft skeleton + model

### LINKED ISSUE #109: New draft skeleton + model
EDIT by @santiagohermo: We are broadening the goals of this task, which is now tracked by #107. In here we will:

- Start over with the draft, following [this structure](https://github.com/diegogentilepassaro/min_wage_rent/issues/109#issuecomment-877959050)
- Add model @santiagohermo has been thinking about in #95 to it

Opened branch `#109_new_draft_skeleton` for related work.

----

[Goals]
Plan the write-up of the next draft and obtain a roadmap with a checklist of the sections and the ideal figures and tables to add in each section. 

[Output]
- A chronological list of sections, with titles. For each section, a list of tables and figures that will live there. Ideally, we could even have a sentence explaining the pitch and aim of each section and object within. 

[Notes]
- Based on the output of this issue we will open the necessary tasks to build the objects that will populate the draft. We will track those tasks  in #107, so the output of this issue is the main input of #107.

### PR DESCRIPTION
**Pull request by santiagohermo**
Can you review this PR @diegogentilepassaro? Closes #109. 

The changes in the branch are as follows:

- I created a skeleton for the paper following https://github.com/diegogentilepassaro/min_wage_rent/issues/109#issuecomment-877959050. We'll fill it out later.
  - I left the current intro, data, and empirical strategy sections. These can be a good starting point for re-writing.
- I completed a pass on the model and the model appendix. Make sure to read this carefully!
- I dropped most figures and tables, which we'll have to add again once we re-build them.

fyi @gabrieleborg

### CODE REVIEW

**Comment by diegogentilepassaro** [comment]
Task received @santiagohermo!

**Comment by diegogentilepassaro** [comment]
@santiagohermo, I have finished with a first pass of this PR. Feel free to to not review points 1. and 2., but I have :

1. Changed the abstract for the one we sent to the lunch. It is not great but better than leaving it blank.
2. Changed some minor things in the introduction. Although, we will rewrite it, it was a while since I read it and I started thinking a bit on how to go about things. The changes I did had a focus on parts that may still be useful for the next iteration.
3. Left a lot of questions and comments in model.tex. We can discuss on the basis of those. 
4. Made a few changes or additions. Mostly minor changes but in a few instances I tried some examples and explanations that I thought were important. 

let me know your thoughts :D

**Comment by santiagohermo** [comment]
Thanks for the careful read @diegogentilepassaro! I went through your  comments and edits. Two main things:

1. Did you go through the dynamic model in the appendix? I didn't see any comments there, and I think we want to check that as well.
2. I implemented some of your suggestions, some I did not, and some I replies to continue the discussion. When you go through my replies, feel free to delete notes in which you think we converged.

Replies to your general comments [above](https://github.com/diegogentilepassaro/min_wage_rent/pull/116#issuecomment-917228219).

> 1. Changed the abstract for the one we sent to the lunch. It is not great but better than leaving it blank.

Great!

> 2. Changed some minor things in the introduction. Although, we will rewrite it, it was a while since I read it and I started thinking a bit on how to go about things. The changes I did had a focus on parts that may still be useful for the next iteration.

I ignored this, so that we focus on the model and merge this issue. Will think about it in #112.

> 3. Left a lot of questions and comments in model.tex. We can discuss on the basis of those.
> 4. Made a few changes or additions. Mostly minor changes but in a few instances I tried some examples and explanations that I thought were important.

I replied and made changes. Some it might be more efficient to tackle tomorrow in the office!

**Comment by diegogentilepassaro** [comment]
Thanks @santiagohermo! I just went through the comments and resolved most by just deleting our discussion. For the remaining we can meet tomorrow :D

As for the appendix, I will review that ASAP. Sorry that I've missed it!

**Comment by santiagohermo** [comment]
FYI @gabrieleborg: We solved the remaining issues in person with @diegogentilepassaro. I think you can give a look at the model in a more advanced version of the draft.

Closing this task.

**Comment by santiagohermo** [comment]
Summary [here](https://github.com/diegogentilepassaro/min_wage_rent/issues/109#issuecomment-919509713)

**Pull request merged**
